### PR TITLE
fix: IllegalArgumentException when retrieving media duration

### PR DESCRIPTION
**Pull request by nqmgaming**

### CODE REVIEW

**Comment by nqmgaming** [comment]
fix: item selected not update after delete

https://github.com/aarash709/VoiceRecorder/assets/94773751/af24c0aa-c211-4df2-9f5d-418ca4596508

**Comment by nqmgaming** [comment]
I just fix issue spam but it still error, I tried to make it as error-free as possible when users spam recordings

**Comment by nqmgaming** [comment]
I think you should make two screen
- 1. List
- 2. Record

**Comment by nqmgaming** [comment]
I just made the changes as you suggested, 

> The idea is to make the UI more like iOS voice memo app but it eventually have two screens for an expanded recorder controls and better visuals.

How about showing a dialog or bottom sheet to enter the name of the audio file?

**Comment by aarash709** [comment]
> I just made the changes as you suggested,
> 
> > The idea is to make the UI more like iOS voice memo app but it eventually have two screens for an expanded recorder controls and better visuals.
> 
> How about showing a dialog or bottom sheet to enter the name of the audio file?

@nqmgaming Thanks for your feedback. It already has a bottom sheet for renaming. I`m gonna look into options to make editing files simpler and look similar to iOS voice memo app.

**Pull request merged**
